---
- name: Create Application Database
  mysql_db: name={{dbname}} state=present

- name: Create Application DB User
  mysql_user: name={{dbuser}} password={{upassword}}
          priv=*.*:ALL host='%' state=present

- name: Copy database over
  copy: src=annuaire.sql dest=/tmp/annuaire.sql

- name: Import data
  mysql_db: name=annuairedb state=import target=/tmp/annuaire.sql

- name: Copy PHP page
  copy: src=page.php dest=/var/www/html/page.php
  notify:
    - Redemarrage de Apache
