---
- name: Installation de PHP et des extensions
  ansible.builtin.package:
    name: "{{ liste_package_php }}"
    state: present

- name: Redemarrer Apache
  ansible.builtin.service:
    name: "{{ service_apache }}"
    state: restarted

 #- name: Installation de PHP et des extensions
 #  ansible.builtin.package:
 #    name:
 #      - php
 #      - php-pdo
 #      - php-mysql
 #      - php-soap
 #      - php-gd
 #    state: present
...
