---
- name: Créer l'utilisateur pour la base de données
  community.mysql.mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: '*.*:ALL'
    host: 'localhost'
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
    column_case_sensitive: false
  no_log: true

- name: Créer la base de données
  community.mysql.mysql_db:
    name: "{{ dbname }}"
    login_user: "{{ dbuser }}"
    login_password: "{{ upassword }}"
    state: present
  no_log: true

- name: Copier le fichier annuaire
  ansible.builtin.copy:
    src: annuaire.sql
    dest: /tmp/annuaire.sql
    mode: "00664"

- name: Importer les données
  community.mysql.mysql_db:
    name: "{{ dbname }}"
    state: "import"
    target: "/tmp/annuaire.sql"
    login_user: "{{ dbuser }}"
    login_password: "{{ upassword }}"
  no_log: true

- name: Copier la page PHP
  ansible.builtin.template:
    src: page.php
    dest: /var/www/html/page.php
    mode: "00664"
  notify: Redemarrer Apache
...
