---
- name: Installer MariaDB
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ liste_package_mariadb }}"

- name: Démarrer MariaDB
  service:
    name: mariadb
    state: started
    enabled: true
...
