---
- name: Créer la base de données
  mysql_db:
    name: "{{dbname}}"
    state: present

- name: Créer l'utilisateur pour la base de données
  mysql_user: name={{dbuser}} password={{upassword}}
          priv=*.*:ALL host='localhost' state=present
  no_log: yes 

- name: Copier le fichier annuaire
  copy:
    src: annuaire.sql
    dest: /tmp/annuaire.sql

- name: Importer les données
  mysql_db: name={{dbname}} state=import target=/tmp/annuaire.sql

- name: Copier la page PHP
  template:
    src: page.php
    dest: /var/www/html/page.php
  notify: Redemarrer Apache
...
