---
- name: Installer MariaDB
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ liste_package_mariadb }}"

- name: Démarrer MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
...
